Exercise #2 is done
zvezd04et/newsleak pull request #1
Opened 2018-09-25 04:59 UTC by zvezd04et

I optimized the screen on the density of xhdpi and xxhdpi

2018-09-25 07:37 UTC, MaxHlystov commented
Не увидел косяков. Прикольно, что разделил фотку и остальной текст на разные xml-ки.

2018-09-25 22:39 UTC, PStrelchenko requested changes
Выглядит неплохо =) Но требуются правки.

2018-09-25 22:39 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/exercise_2/MainActivity.java
> +        emailBtn.setOnClickListener(new View.OnClickListener() {
Проверь на утечки памяти при повороте, почитать про это можно тут: https://blog.mindorks.com/detecting-and-fixing-memory-leaks-in-android.

2018-09-25 22:39 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/exercise_2/MainActivity.java
> +        emailBtn.setOnClickListener(new View.OnClickListener() {
Аналогично в других местах задания onClickListener

2018-09-25 22:39 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/exercise_2/MainActivity.java
> +        vkLogo.setOnClickListener(new View.OnClickListener() {
Подключи возможность использования Java 8 -- чтобы вместо этой большой и неудобной конструкции можно будет использовать лямбды =)

vkLogo.setOnClickListener( v -> { ... } )

2018-09-25 22:39 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/exercise_2/MainActivity.java
> +import android.widget.Toast;
А где иконочки соц.сетей? =(((

2018-09-25 22:39 UTC, PStrelchenkoHH commented on app/src/main/res/layout/common_content.xml
> +            android:layout_marginTop="4dp"
Размер - в dimens.

2018-09-25 22:39 UTC, PStrelchenkoHH commented on app/src/main/res/layout/common_content.xml
> +        <ImageView
И кажется, схожий функционал можно было сделать на одном TextView при помощи compoundDrawable. Погугли "android textview compound drawable". Если не разберешься - пиши мне, разберемся вместе.

2018-09-25 22:39 UTC, PStrelchenkoHH commented on app/src/main/res/layout/common_content.xml
> +            android:layout_marginTop="4dp"
Смущает наличие margin = 4. В задании вроде сказано, что все маргины, кроме определенных, равны 16.

2018-09-25 22:39 UTC, PStrelchenkoHH commented on app/src/main/res/layout/common_content.xml
> +    <!--<TextView-->
Закомментированный код обычно и не нужен =) Удали.

2018-09-25 22:39 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/exercise_2/MainActivity.java
> +import android.widget.Toast;
Я имею в виду, помимо vk =) Неужели больше нету? =)

2018-09-25 22:39 UTC, PStrelchenkoHH commented on app/src/main/res/values-xhdpi/dimens.xml
> +<resources>
На лекции говорили, что такие квалификаторы (-xhdpi, -large, -small) уже не надо использовать. Вместо них нужно использовать -sw , -h и прочие.

2018-09-25 22:39 UTC, PStrelchenkoHH commented on app/src/main/res/values/strings.xml
> +    <string name="email_address" translatable="false">a.petronenko@gmail.com</string>
Я бы вынес url для VK в код. Это же константное значение, зачем его хранить здесь, в ресурсах приложения?

2018-09-29 12:30 UTC, PStrelchenko requested changes

2018-09-29 12:30 UTC, PStrelchenko commented on app/src/main/java/com/z/exercise_2/MainActivity.java
> +        final Intent intent = new Intent(Intent.ACTION_SENDTO)
А зачем тут final?

2018-09-29 12:30 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/exercise_2/MainActivity.java
> +                .putExtra(Intent.EXTRA_SUBJECT, getString(R.string.email_subject))
У тебя отправка email-а с сообщением работает? 
Если не заработает - вот здесь - https://medium.com/@cketti/android-sending-email-using-intents-3da63662c58f - можно посмотреть альтернативный способ. И по идее, он даже правильнее, чем через EXTRA. У некоторых студентов не отправлялось сообщение.

2018-09-29 12:30 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/exercise_2/MainActivity.java
> +        final Intent intent = new Intent(Intent.ACTION_VIEW);
Зачем тут final?

2018-09-29 12:30 UTC, PStrelchenkoHH commented on app/src/main/res/values/strings.xml
> +    <string name="email_address" translatable="false">a.petronenko@gmail.com</string>
Вынести можно и email - зачем он в ресурсах?

2018-09-29 12:30 UTC, PStrelchenkoHH commented on app/src/main/res/values/strings.xml
> +    <string name="vk_url" translatable="false">https://vk.com/id1748403</string>
забытая ссылка на VK.

2018-09-29 12:30 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/exercise_2/MainActivity.java
> +        Intent intent = new Intent(Intent.ACTION_VIEW, uri).setPackage(appPackage);
Два вопроса - 
1) зачем в этом методе `stringUrl` - если ты хочешь запустить приложение, а не браузер?
2) уверен ли ты, что именно так запускаются другие приложения? Глянь ссылку - https://stackoverflow.com/questions/3872063/launch-an-application-from-another-application-on-android

2018-09-30 07:49 UTC, zvezd04et commented on app/src/main/java/com/z/exercise_2/MainActivity.java
> +        final Intent intent = new Intent(Intent.ACTION_SENDTO)
Я же тебе уже сказал, что скопировал весь код из as is из домашки Сергея:
https://github.com/Android-Academy-MSK/Lecture1-Exercise/blob/master/app/src/main/java/ru/androidacademy/msk/lecture1/exercise/PreviewActivity.java

Он на первой лекции сказал, что будет делиться best practices, а это именно то за чем я пришел =)

Но я решил разобраться в вопросе - глянь, плиз:
https://softwareengineering.stackexchange.com/questions/115690/why-declare-final-variables-inside-methods

http://www.javapractices.com/topic/TopicAction.do?Id=23

Считаешь, что использование final лишнее? Поясни, плиз

2018-09-30 08:55 UTC, zvezd04et commented on app/src/main/java/com/z/exercise_2/MainActivity.java
> +                .putExtra(Intent.EXTRA_SUBJECT, getString(R.string.email_subject))
Это тоже скопировано =) Но у меня и в первой домашке так было и тогда ты этот момент не прокомментировал:
https://github.com/zvezd04et/android-academy_lecture01-exercise/blob/master/app/src/main/java/com/z/exercise1/PreviewActivity.java

Паша, я пришел научиться и, конечно же, все проверяю. Причем не только на своем телефоне и планшете. У некоторых студентов, возможно, не было этой строчки:
intent.setData(Uri.parse("mailto:"));
Если не применить метод setData с Uri.parse("mailto:"), то почтовое приложение не будет обнаружено. Я коментил эту строчку и таким образом Toast проверял =)

Если я правильно понял, то в статье говорится, что если юзать EXTRA_SUBJECT, EXTRA_TEXT, то есть риски, так как эти возможность не задокументированы, что контент не перенесется, а не то что приложение не запустится. Но он не говорит, что использование параметризованной строки mailto документировано. И я сам не смог найти, можешь скинуть документацию?
А так само использование интента и у меня, и в статье одинаковое:

Intent emailIntent = new Intent(Intent.ACTION_SENDTO);
emailIntent.setData(Uri.parse(mailto));

У меня на телефоне несколько почтовых клиентов, и я решил проверить, может используя способ из статьи, система предложит выбрать приложение или запустит по умолчанию. Нет, все так же, как и с использованием putExtra.

2018-09-30 08:56 UTC, zvezd04et commented on app/src/main/java/com/z/exercise_2/MainActivity.java
> +        final Intent intent = new Intent(Intent.ACTION_VIEW);
см. выше

2018-09-30 09:01 UTC, zvezd04et commented on app/src/main/res/values/strings.xml
> +    <string name="email_address" translatable="false">a.petronenko@gmail.com</string>
Когда делал первую домашку я не знал, где правильно размещать email, поэтому там, вообще, его не указывал. Типа должен ввести пользователь. 

Но потом Сергей выложил решение, и я оттуда перетащил:
https://github.com/Android-Academy-MSK/Lecture1-Exercise/blob/master/app/src/main/res/values/strings.xml

Считаешь, что лучше будет в коде?

2018-09-30 09:04 UTC, zvezd04et commented on app/src/main/res/values/strings.xml
> +    <string name="vk_url" translatable="false">https://vk.com/id1748403</string>
Спасибо, удалил

2018-09-30 09:09 UTC, zvezd04et commented on app/src/main/java/com/z/exercise_2/MainActivity.java
> +        Intent intent = new Intent(Intent.ACTION_VIEW, uri).setPackage(appPackage);
1. Надо же как-то сообщить приложению чей профайл открывать, есть другой способ?

2. По ссылке просто запуск приложения, но задача открыть нужный профайл. Я гуглил "how open telegram app".
https://stackoverflow.com/questions/35721942/how-to-launch-telegram-app-from-my-own-android-application

Поясни, плиз, что в ответе не правильно...

2018-09-30 11:25 UTC, PStrelchenko approved these changes
Вперед к третьей ДЗ.

2018-09-30 11:25 UTC, PStrelchenko commented on app/src/main/java/com/z/exercise_2/MainActivity.java
> +        final Intent intent = new Intent(Intent.ACTION_SENDTO)
Считаю, что лишнее, потому что ни на что здесь не влияет. Компилятор его не требует конкретно здесь. 
С точки зрения Effective Java - да, ок, надо все переменные, все методы, все классы объявлять final. Если уж объявлять - то объявлять все. 

В Kotlin-е это идет из коробки - там линтер заставляет тебя писать val вместо var там, где это возмдожно, в Kotlin из коробки все классы и методы являются final. 
В Java же можно этого не делать. 

К чему веду - если пишешь в стиле Effective Java -> велкам, но тогда надо страться везде придерживаться этого правила, не только с локальными переменными.

2018-09-30 11:25 UTC, PStrelchenko commented on app/src/main/java/com/z/exercise_2/MainActivity.java
> +                .putExtra(Intent.EXTRA_SUBJECT, getString(R.string.email_subject))
В канале mentor-strelchenko отписал по этому поводу. 

1) судя по документации ACTION_SENDTO - то, что с этим action-ом можно юзать EXTRA_TEXT, EXTRA_SUBJECT и тп - это незадокументированная фича, которой пользуются некоторые почтовые приложения. https://developer.android.com/reference/android/content/Intent.html#ACTION_SENDTO
2) Все почтовые приложения должны поддерживать стандарт RFC 6068 (https://tools.ietf.org/html/rfc6068) - и судя по этой таблице (https://github.com/cketti/EmailIntentBuilder/wiki/EmailClientCompatibilityList) - они и поддерживают. Таблице уже 2 года, возможно, что-то изменилось в лучшую сторону. 
3) Из этого делаю вывод, что надо все-таки использовать построение URI с `mailTo:`, чтобы поддержать как можно больше почтовых клиентов. 

Для большинства почтовых клиентов и способ с заданием полей через `Intent.EXTRA_` тоже сработает.

2018-09-30 11:25 UTC, PStrelchenko commented on app/src/main/java/com/z/exercise_2/MainActivity.java
> +        final Intent intent = new Intent(Intent.ACTION_VIEW);
См. выше.

2018-09-30 11:25 UTC, PStrelchenko commented on app/src/main/java/com/z/exercise_2/MainActivity.java
> +        Intent intent = new Intent(Intent.ACTION_VIEW, uri).setPackage(appPackage);
Здесь все ок, мой косяк. Оставь как есть.

2018-09-30 11:25 UTC, PStrelchenko commented on app/src/main/res/values/strings.xml
> +    <string name="email_address" translatable="false">a.petronenko@gmail.com</string>
Считаю, что лучше в коде, потому что "зачем использовать Context там, где он не нужен"? 
С точки зрения поддержки - оба решения равноценны. Чтобы поменять константу в коде - придется перевыложить приложение, чтобы поменять константу в strings.xml - придется поменять константу в коде. Так что - разницы особой нет. 

Разница в получении этой константы. Чтобы достать ее из strings.xml - придется ипользовать объект Context. Чтобы достать ее из кода - не потребуется Context.

2018-09-30 19:43 UTC, merged