Feature/ex 3
zvezd04et/newsleak pull request #2
Opened 2018-10-06 13:42 UTC by zvezd04et

ex 3 is done

2018-10-07 11:21 UTC, PStrelchenko requested changes
Нужны правки

2018-10-07 11:21 UTC, PStrelchenko commented on app/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-alpha2'
Не рекомендую использовать alpha-версии библиотек.

2018-10-07 11:21 UTC, PStrelchenko commented on app/build.gradle
> +    implementation 'com.github.bumptech.glide:glide:4.4.0'
Android studio подсказывает, что у glide-а есть версия 4.5.0.
А оф. документация подсказывает, что вообще есть 4.7.1 
Что тебя остановило от использования последней версии?

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".NewsDetailsActivity"></activity>
пустой тэг можно писать в сокращенном виде - <activity ... />

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsDetailsActivity.java
> +    public static void start(@NonNull Activity activity, @NonNull NewsItem newsItem) {
Сюда не обязательно передавать именно класс `Activity`, можно обойтись `Context`-ом.

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsListActivity.java
> +    private final NewsListAdapter.OnItemClickListener clickListener = newsItem ->
Не нужно делать click listener-ы в виде полей Activity. Это логически отрывает clickListener от его контекста - его адаптера.

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsListActivity.java
> +            default:
я бы добавил пустую строчку перед default, чтобы отделить разные case-ы друг от друга + добавил бы логирование в блок default, что был встречен неизвестный кейс

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsListActivity.java
> +        list.setAdapter(new NewsListAdapter(this, DataUtils.generateNews(), clickListener));
По заданию надо было добавить ItemDecorator. Вэйр из ит?

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +    private final LayoutInflater inflater;
Inflater получишь в другом методе, не надо хранить его в адаптере

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +        this.inflater = LayoutInflater.from(context);
Inflater не нужно получать здесь - его надо получать в методе onCreateVewHolder из контекста parent

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +        this.imageLoader = SupportUtils.getImageLoader(context);
Лучше передавать сюда уже готовый imageloader, и просто сохранять его в поле. Освободи адаптер от ненужной ему логики

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +            case 3:
Не используй "магические числа" - плохая практика. Всегда именуй подобные константы.

Я бы вообще NewsCategory сделал бы enum-ом. По смыслу очень подходит здесь.

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +        private final ImageView photoView;
Проставь аннотации `@NonNull` над полями.

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +        void bind(@NonNull NewsItem newsItem) {
метод можно сделать private

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +        void onItemClick(NewsItem newsItem);
Аннотацию `@NonNull` на параметре добавь

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +public class SupportUtils {
Утилитный класс - добавляй private конструктор. Можно в нем дополнительно бросать исключение, чтоб никто наверняка не пользовался этим конструктором. Например IllegalAccessError

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +        boolean xlarge = ((context.getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) == 4);
Похоже, что `context.getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK` можно вынести в отдельный метод - с каким-нибудь понятным именем.

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +    public static int getDisplayColumns(@NonNull Activity activity) {
В качестве параметра здесь можно передать `Context`, а не `Activity`.

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +    public static String getFormatPublishDate(@NonNull Date publishDate) {
Аннотацию `@NonNull` над методом добавь

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +        DateFormat timeInstance = DateFormat.getTimeInstance(DateFormat.SHORT, Locale.getDefault());
Можно вынести в отдельное статическое поле внутри класса SupportUtils -> не обязательно при каждом форматировании создавать новый объект `DateFormat`

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +    public static RequestManager getImageLoader(@NonNull Context context) {
Аннотацию `@NonNull`над методом

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/data/Category.java
> +public class Category implements Serializable {
Я бы переписал это на enum. Подходит по смыслу потому что - у тебя есть некоторое ограниченное множество констант с заданными id, с заданными именами. 
И вместо того, чтобы завязываться на id == 3, ты будешь оперировать более высокоуровневыми сущностями с понятными именами.

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/data/DataUtils.java
> +                createDate(2018, 10, 6, 10, 34),
Чтобы иметь возможность потестить в любой день форматирование даты - допиши код, чтобы первая новость всегда, вне зависимости от текущего дня, была 4 часа назад, вторая - всегда была вчера, третья - несколько дней назад.

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/data/DataUtils.java
> +    private static Date createDate(int year, int month, int date, int hrs, int min) {
Аннотацию `@NonNull` добавляй

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/data/NewsItem.java
> +    private final String title;
Аннотации `@NonNull` над всеми полями, над всеми `get`-методами.

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/res/layout/animal_item_news.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Зачем нужна была обертка над CardView?

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/res/layout/animal_item_news.xml
> +    android:layout_height="@dimen/news_item_height"
Не думаю, что здесь обязательно нужно ограничивать высоту, чтобы добиться фиксированной высоты карточки

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/res/layout/default_item_news.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Аналогичные вопросы про LinearLayout и фиксированную высоту

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/res/layout/default_item_news.xml
> +        android:layout_gravity="center"
Зачем здесь этот аттрибут? Вроде ни на что не влияет, раз у тебя ширина = match_parent

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/res/layout/default_item_news.xml
> +    <androidx.cardview.widget.CardView xmlns:card_view="http://schemas.android.com/apk/res-auto"
Обычно пути к схемам XML (xmlns:card_view ..) помещают в самом верхнем тэге. чтобы они действовали на всех потомков.

2018-10-07 11:21 UTC, PStrelchenko commented on app/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-alpha2'
И, кстати, не увидел в проекте ни одного ConstraintLayout-а. 
Зачем тогда он подключен? Если уж подключил - то пользуйся. А если нет - то выкидывай

2018-10-07 11:21 UTC, PStrelchenko commented on app/build.gradle
> +android.applicationVariants.all { variant ->
Этот блок кода выполняется при каждой сборке. Это реально нужно?

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +        switch (viewType) {
Добавляем default ветку с комментарием. Чтобы в случае чего узнать

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +        public ViewHolder(@NonNull View itemView, @Nullable OnItemClickListener listener) {
Необязательно сюда пробрасывать listener - у тебя класс не статический, а внутренний - ему будут доступны все поля адаптера.

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +        boolean xlarge = ((context.getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) == 4);
Что такое "4"?.. Именуй эти "магические числа" как-нибудь понятно.

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +        boolean xlarge = ((context.getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) == 4);
Точнее, поищи среди стандартных констант.

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +    public static String getFormatPublishDate(@NonNull Date publishDate) {
И я бы вынес этот метод в какой-нибудь другой Utils класс, потому что твой класс SupportUtils начинает превращаться в винегрет - ты сюда складываешь все утилитные функции, которые тебе нужны. Не надо так. Заведи, например, DateUtils для утилитных функций, связанных с датами. DeviceUtils - для функций, связанных с устройством.

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +    public static RequestManager getImageLoader(@NonNull Context context) {
Этот метод тоже можно в другой какой-то утилитный класс вынести - типо ImagesLoadingUtils

2018-10-07 11:21 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +        boolean large = ((context.getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) == Configuration.SCREENLAYOUT_SIZE_LARGE);
Вопрос - а надо ли определять, что устройство является планшетом? Может лучше завязаться на ширину? И расчитывать число колонок исходя из доступной ширины устройства?

2018-10-07 11:22 UTC, PStrelchenko commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
зачем нужна эта зависимость?

2018-10-08 17:52 UTC, zvezd04et commented on app/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:2.0.0-alpha2'
Выкинул

2018-10-08 18:16 UTC, zvezd04et commented on app/build.gradle
> +    implementation 'com.github.bumptech.glide:glide:4.4.0'
Ничего не останавливало. Прост чет даже не подумал, что это так важно для учебных целей, и скопировал отсюда:
https://github.com/Android-Academy-MSK/Lecture3-Code/blob/master/app/build.gradle

Включил в studio проверку обновлений зависимостей

Версию glide обновил до 4.8.0

2018-10-08 18:46 UTC, zvezd04et commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
я так понимаю она в androidx пришла на смену com.android.support:support-v4.

А com.android.support:support-v4 нужна для поддержки API от 14 и старше, но у нас в учебном проекте minSdkVersion 21, поэтому можно удалять, так?

2018-10-08 18:48 UTC, zvezd04et commented on app/build.gradle
> +android.applicationVariants.all { variant ->
Но это же не сильно замедляет сборку =))

Я же тебе говорил, что отпавляю apk друзьям, чтобы проверять как у них работает приложение, а так мне проще ориентироваться, кому что и какой версии отправлял

2018-10-08 19:20 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/NewsListActivity.java
> +        list.setAdapter(new NewsListAdapter(this, DataUtils.generateNews(), clickListener));
Добавил

2018-10-08 19:56 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +            case 3:
Пока переделал на константу.

Есть подозрение, что категории, как справочная информация будет тянутся из новостного агрегатора. И я как понимаю, это в качестве обучения, для обкатки навыка подмены вью. 

Пока нарушает единообразие, а я не придумал, как сделать, чтобы смотрелось красиво =))

2018-10-08 20:10 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +        void onItemClick(NewsItem newsItem);
Добавил

2018-10-08 20:11 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +    public static String getFormatPublishDate(@NonNull Date publishDate) {
Аннотацию добавил

2018-10-08 20:16 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +    public static String getFormatPublishDate(@NonNull Date publishDate) {
Я думал об этом, но не будет ли винегрет из классов содержащих один метод? У вас на практике такое применяется? Много у вас классов с одним методом?

У меня был план собирать в одном классе, а уже потом по мере группировки в логические сущности расстаскивать по классам.

2018-10-08 20:17 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +    public static RequestManager getImageLoader(@NonNull Context context) {
Добавил

2018-10-09 03:56 UTC, zvezd04et commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".NewsDetailsActivity"></activity>
схлопнул

2018-10-09 04:09 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/NewsDetailsActivity.java
> +    public static void start(@NonNull Activity activity, @NonNull NewsItem newsItem) {
Я выбрал путь следования best practies с лекций =)

Но все равно Activity является подклассом Context, а сюда я передаю NewsListActivity.this, что и является контекстом в моем понимании.

Что ты имеешь в виду? Как сделать по-другому? И зачем?

2018-10-09 04:22 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/NewsListActivity.java
> +            default:
Добавил

Но мне кажется там трудно будет выбрать что-то не то =)

2018-10-09 04:26 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +        private final ImageView photoView;
добавил

2018-10-09 04:31 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +        void bind(@NonNull NewsItem newsItem) {
сделал

2018-10-09 04:50 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +public class SupportUtils {
Добавил

2018-10-09 05:04 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +        boolean xlarge = ((context.getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) == 4);
Нашел, исправил

2018-10-09 05:06 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +    public static RequestManager getImageLoader(@NonNull Context context) {
Если практика создания классов с единственным методом - это норм, то раскидаю, делов-то.

Но меня пока это немного смущает

2018-10-09 05:08 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +        boolean large = ((context.getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) == Configuration.SCREENLAYOUT_SIZE_LARGE);
В домашке было сказано проверить на планшет, и добавить количество колонок для альбомной ориентации и для телефона, как я понял

Что собственно и сделал

2018-10-09 05:10 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +        boolean xlarge = ((context.getResources().getConfiguration().screenLayout & Configuration.SCREENLAYOUT_SIZE_MASK) == 4);
Вынес в переменную

2018-10-09 05:12 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +    public static int getDisplayColumns(@NonNull Activity activity) {
А в чем профит?

Я делал, чтоб было в едином стиле со start для activity

2018-10-09 05:22 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +        DateFormat timeInstance = DateFormat.getTimeInstance(DateFormat.SHORT, Locale.getDefault());
Вынес

2018-10-09 05:24 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/data/Category.java
> +public class Category implements Serializable {
Я думаю, что эти классы будут выпиливаться, когда мы начнем тянуть новости с агрегатора. Очень похоже что это будет как тэги, которые могут меняться

2018-10-09 05:26 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/data/DataUtils.java
> +                createDate(2018, 10, 6, 10, 34),
Зачем заведомо писать мертвый код?

Мы же начнем тянуть актуальные новости.

Времени с работой и так не хватает =(

2018-10-09 05:36 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/data/DataUtils.java
> +    private static Date createDate(int year, int month, int date, int hrs, int min) {
Добавил

Я использую функцию AS Analyze -> Infer Nullity. Она эти моменты пропускает. 

И здесь NoNull кажется очевидным, это не слишком избыточно?
Гайда, чем руководствоваться при расстановке аннотаций, я так и не нашел.

2018-10-09 05:36 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/data/NewsItem.java
> +    private final String title;
Добавил

2018-10-09 05:50 UTC, zvezd04et commented on app/src/main/res/layout/animal_item_news.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Я добавлял layout следующим образом ПКМ в папке layout -> New -> XML -> Layout XML file.
Эта операция по умолчанию добавляет LinearLayout. Потом я в редакторе перетащил на него  CardView.

Сейчас попробовал удалить LinearLayout - редактор не дает перетащить CardView. При добавлении вручную ругается AS.

И в гайде так:
https://developer.android.com/guide/topics/ui/layout/cardview

Можешь показать рабочий пример использования CardView без обертки?

2018-10-09 05:54 UTC, zvezd04et commented on app/src/main/res/layout/animal_item_news.xml
> +    android:layout_height="@dimen/news_item_height"
Не думаешь, ок. Но как ты ожидаешь, чтобы я отреагировал на этот комментарий?

Я следую best practices с лекций. Других руководств к оформлению у меня нет =)
https://github.com/Android-Academy-MSK/Lecture3-Code/blob/master/app/src/main/res/layout/item_actor.xml

2018-10-09 05:54 UTC, zvezd04et commented on app/src/main/res/layout/default_item_news.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Аналогичный ответ и встречный вопрос =)

2018-10-09 06:02 UTC, zvezd04et commented on app/src/main/res/layout/default_item_news.xml
> +        android:layout_gravity="center"
Удалил

2018-10-09 06:07 UTC, zvezd04et commented on app/src/main/res/layout/default_item_news.xml
> +    <androidx.cardview.widget.CardView xmlns:card_view="http://schemas.android.com/apk/res-auto"
Добавил по аналогии с https://developer.android.com/guide/topics/ui/layout/cardview

2018-10-09 06:10 UTC, PStrelchenkoHH commented on app/build.gradle
> +android.applicationVariants.all { variant ->
Ок, про apk друзьям вылетело из головы.

2018-10-09 06:13 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/newsleak/NewsDetailsActivity.java
> +    public static void start(@NonNull Activity activity, @NonNull NewsItem newsItem) {
Предположим, что тебе потребуется написать код для обработки deep link-а, который должен будет открыть эту activity. В `BroadcastReceiver` тебе придет `Context`, а не `Activity`.  Почему бы не изменить параметр на более абстактный и из коробки получить возможность открывать эту `activity` из разных мест приложения, а не только из `Activity`?

2018-10-09 06:13 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +        switch (viewType) {
Добавил

2018-10-09 06:15 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/newsleak/NewsListActivity.java
> +            default:
Практика показывает, что если не добавляешь что-то сразу, то потом вообще ничего не исправляешь еще очень долгое время. 
А так - сделал default, и даже если забыл обработать, то хотя бы у себя в логах это увидеть можно.

2018-10-09 06:20 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +    public static int getDisplayColumns(@NonNull Activity activity) {
Всегда лучше завязываться на более абстрактные модели, чем на конкретные. 
Передав сюда `context`, ты получаешь возможность использовать метод и из сервиса, и из `broadcastReceiver`, и из твоих каких-то оберток `application context`-а, и из фрагмента, до отовсюду, где есть хоть какой-то контекст. 
Может возникнуть вопрос в стиле - а нафига мне это надо, если я использую только из `activity` -- для того, чтобы заранее упростить себе какие-то вещи. Я - ленивый человек, мне не хочется потом возвращаться к этому утилитному классу и менять здесь что-то, когда можно этого не делать

2018-10-09 06:30 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +    public static String getFormatPublishDate(@NonNull Date publishDate) {
Практика показывает, что если ты не раскидываешь все сразу нормально - потом приходит кто-нибудь в твой проект и начинает делать так же. В смысле, не раскидывать. Или же ты сам ради ускорения засунешь очередную функцию в утилитный класс. 

Основная мысль - тебе же потом придется потратить на рефакторинг гораздо больше усилий, если ты не сделаешь этого сейчас.
Много ли у нас классов с одним методом - достаточно много. Но это всегда окупается тем, что со временем эти классы начинают дополняться нужными функциями, связанными с той или иной темой. 

В твоем случае -- есть вот даты. Сейчас там только один формат даты. Появится еще один экран - может там будет другой формат, совсем другой. Куда засунешь функцию? Нет DateUtils -> опять положишь в SupportUtils. Появляется третий экран, на котором еще один формат данных. И так далее.
С ImageUtils - сейчас у тебя только 1 метод для requestOptions, а на разных экранах могут понадобиться разные request option-ы.

2018-10-09 06:30 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +    public static RequestManager getImageLoader(@NonNull Context context) {
Отписал выше.

2018-10-09 11:13 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/NewsListActivity.java
> +    private final NewsListAdapter.OnItemClickListener clickListener = newsItem ->
Так строго категорично не нужно? =)

Кликается же NewsListActivity и сразу видно что на Activity навешен listener, разве не логично? =)

Но и помимо логики и удобства у такого способа, есть ряд плюсов:
https://hackernoon.com/4-ways-to-implement-onclicklistener-on-android-9b956cbd2928

И это тоже я утащил, как best practicies:
https://github.com/Android-Academy-MSK/Lecture3-Code/blob/master/app/src/main/java/ru/androidacademy/msk/lists/ActorRecyclerActivity.java

Может такой способ все же имеет право на существование?

2018-10-09 11:30 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +        this.inflater = LayoutInflater.from(context);
Теория, теорией - я решил проверить на практике. Поставил breakpoimts в конструкторе NewsListAdapter и методе onCreateViewHolder. 

Когда мы получаем в конструкторе и сохраняем в поле, то получаем Inflater ровно один раз. А если перенести в onCreateVewHolder, то LayoutInflater будет дергаться для каждого вью.

Профит очевиден.

В чем плюсы переноса в onCreateVewHolder?

2018-10-09 11:30 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +    private final LayoutInflater inflater;
см. ниже

2018-10-09 11:38 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +        this.imageLoader = SupportUtils.getImageLoader(context);
Так imageloader нужен только в адаптере, почему не логично?

Дернуть imageloader в activity и перекинуть в адаптер немного загромоздит код, не находишь?

Мне кажется это дело вкуса =)

2018-10-09 11:43 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +    public static int getDisplayColumns(@NonNull Activity activity) {
Принял к сведению, спасибо

Возможно ты уже заметил, что я придерживаюсь стиля минимализма и хочу его выдержать.

И то что мне понадобится получить количество колонок не из Activity очень маловероятно =)

2018-10-09 21:15 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +        public ViewHolder(@NonNull View itemView, @Nullable OnItemClickListener listener) {
А вот здесь минимализм, как раз за то, чтобы убрать проброс listener'a =))

Убрал

2018-10-10 05:54 UTC, PStrelchenko requested changes
Последние правки

2018-10-10 05:54 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsListActivity.java
> +    private final NewsListAdapter.OnItemClickListener clickListener = newsItem ->
Ок, я перестану быть категоричным. 
Кратко: ок, такой способ имеет право на существование. Потому что: 

а) это будет работать
б) действительно, такой объект можно навесить не на один, а на несколько объектов (если им потребуется одинаковая обработка).

В статье, также, говорится, что это ведет к уменьшению метода `onCreate`. 

Все это правда. То есть, каких-то, действительно, строгих аргументов "против" я привести не могу - и ты можешь оставить код как есть.

Теперь мои рассуждения.

Приложение, если оно кому-то нужно, растет. Обвешивается дополнительным функционалом, пишутся дополнительные строчки кода.
Со временем Activity разрастается, в него добавляются все новые и новые поля, все новые и новые Intent-ы, появляется куча способов придти в Activity, куча способов уйти с нее. Кода становится больше и ориентироваться в нем становится сложнее. Если оставлять обработку кликов в переменных - эти обработчики, как мне кажется, будут просто сливаться с обычными переменными:

```
public class MyActivity extends AppCompatActivity {

    @NonNull
    private static final EXTRA_FLAG_1_KEY = "flag_1";
    
    @NonNull
    private static final EXTRA_FLAG_2_KEY = "flag_2";
    
    @NonNull
    private static final EXTRA_FLAG_3_KEY = "flag_3";
    
    @NonNull
    private static final EXTRA_FLAG_4_KEY = "flag_4";
    
    @NonNull
    private static final EXTRA_FLAG_5_KEY = "flag_5";
    

    @NonNull
    public static Intent newInstanceWithFlag1(@NonNull Context context, boolean flag1) {
    	Intent intent = new Intent(context, MyActivity.class);

    	Bundle args = new Bundle();
    	args.put(EXTRA_FLAG_1_KEY, flag1);
    	intent.setArguments(args);

    	return intent;
    }

    @NonNull
    public static Intent newInstanceWithFlag2(@NonNull Context context, int flag2) {
    	Intent intent = new Intent(context, MyActivity.class);

    	Bundle args = new Bundle();
    	args.put(EXTRA_FLAG_2_KEY, flag2);
    	intent.setArguments(args);
    	
    	return intent;
    }

    @NonNull
    public static Intent newInstanceWithFlag1(@NonNull Context context, @NonNull String flag3) {
    	Intent intent = new Intent(context, MyActivity.class);

    	Bundle args = new Bundle();
    	args.put(EXTRA_FLAG_3_KEY, flag3);
    	intent.setArguments(args);
    	
    	return intent;
    }


    private TextView firstTextView;

    private RelativeLayout rootRelativeLayout;

    private TextView secondTextView;

    private TextView thirdTextView;
    
    private TextView fourthTextView;


    private View.OnClickListener firstClickListener = view -> {
    	...
    };

    private View.OnClickListener secondClickListener = view -> {
    	...
    };

    private View.OnClickListener thirdClickListener = view -> {
    	...
    };

    private View.OnClickListener fourthClickListener = view -> {
    	...
    };


    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
    	...
    }

    @Override
    protected void onStart() {
    	...
    }

    @Override
    protected void onPause() {
    	...
    }

}
```

Думаю, достаточно для примера =) 
Основной посыл - я считаю, что когда ты пишешь clickListener среди обычных полей класса - то при расширении класса их будет труднее читать и труднее находить в коде. Когда ты будешь читать метод `onCreate` тебе придется постоянно прибегать к сочетанию клавиш `ctrl + B`, чтобы узнать, какой же обработчик все-таки навесили на кнопку.

Это раз.

Аргумент о том, что "click listener в виде поля способствует переиспользованию", я не учитываю по следующей причине. 
Я немного забегу вперед и расскажу про сочетание букв "MVP". Model-View-Presenter. Это архитектурный шаблон, которого придерживаются большинство android приложений. Суть в том, чтобы отделить обработку бизнес-логики от логики отображения и логики получения/отправки данных.
В этом шаблоне твои клики будут ловиться на стороне View (обычно это - activity или fragment), а обрабатываться на стороне `presenter`-а -- специальной сущности, которая служит мостиком между View и Model, и занимается обработкой всех пользовательских сценариев. И ты будешь переиспользовать функции `presenter`-а, а не функции внутри `View`. 

Аргумент по поводу "мокания" метода при помощи PowerMock, если он является полем класса.
Можно послушать подкаст Android Dev - выпуски про тестирование (более свежий -- https://androiddev.apptractor.ru/android-dev-podkast-57/) - и услышать о том, что от использования PowerMock стараются уйти, потому что у него есть ряд проблем. А с моканием методов `Presenter`-а при помощи stub-ов или mockito вообще-то никаких проблем нет, потому что его методы обычно не private. 

Как-то так. Я понимаю, что мои аргументы (труднее ориентироваться в коде, если установка клика и его обработка визуально находятся не рядом + переиспользование функций должно быть на уровне презентера) могут показаться тебе неубедительными, потому что приложение, которое ты пишешь в данный момент состоит всего из пары-тройки классов, суммарная длина которых не составляет и 1000 строк. Но когда ты будешь работать в большом проекте, тебе будет проще в это поверить =)

2018-10-10 05:54 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsListActivity.java
> +        list.setAdapter(new NewsListAdapter(this, DataUtils.generateNews(), clickListener));
Гут, вижу

2018-10-10 05:54 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +    private final LayoutInflater inflater;
Снимаю возражение, внимательно посмотрел как сам делаю на проектах - действительно, стараюсь получать его только один раз.

2018-10-10 05:54 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +        this.inflater = LayoutInflater.from(context);
Ни в чем, действительно. Снимаю замечание, хорошо, что разобрался.

2018-10-10 05:54 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +        this.imageLoader = SupportUtils.getImageLoader(context);
Йеп, дело вкуса. 

Моя логика (мой вкус :)) была в том, чтобы адаптер был как можно "глупее", и как можно меньше знал, откуда берутся компоненты, которые он мог бы использовать. `Activity` - сущность тоже не из самых умных должна быть, но она все же "умнее" адаптера. Поэтому я бы на твоем месте перенес бы создание в `Activity`.

2018-10-10 05:54 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +                Log.d("ViewType", "Get unknown view type");
Утилитка PMD бы тебе сказала, что любой case, если он не заканчивается return-ом, должен иметь `break`. Чтобы избежать неявного поведения.

2018-10-10 05:54 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +        public ViewHolder(@NonNull View itemView, @Nullable OnItemClickListener listener) {
Тоже вкусовщина, оставь как есть.
Я это написал, потому что сам привык уже Adapter-ы писать совсем в другом стиле, в нем у нас listener используется из поля адаптера.

2018-10-10 05:54 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +public class SupportUtils {
Гут

2018-10-10 05:54 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +    public static int getDisplayColumns(@NonNull Activity activity) {
"Никогда не говори "никогда"" =) 
Я б использовал тут context, чтоб в будущем не дергаться.

2018-10-10 05:54 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/SupportUtils.java
> +    public static RequestManager getImageLoader(@NonNull Context context) {
Гут

2018-10-10 05:54 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/data/Category.java
> +public class Category implements Serializable {
Не думаю, что будут выпиливаться. 
Это категория новостей, у каждой новости своя категория. В API NewYork Times (https://developer.nytimes.com/article_search_v2.json#/README) есть News_Desk - раздел новостей. И это явно enum.

В больших приложениях есть практика - получить из network-а одну модельку, а потом ее сконвертировать в представление, удобное для работы на UI. 
И вот мне кажется, что у тебя будет network модель с news_desk, которую можно будет сконвертировать в enum, если для разного типа статей нужно отображать разный UI. 

Почему enum - это хорошо -- потому что это ограниченное множество констант, которые можно будет использовать повсеместно, а при необходимости что-то изменить - потребуется сделать это только в одном месте. Конструкции вида `if ("Criminal".equals(category.name))` тебе отметит любой статический анализатор кода и скажет, что ты используешь какую-то магическую константу.

2018-10-10 05:54 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/data/DataUtils.java
> +                createDate(2018, 10, 6, 10, 34),
Как хочешь, конечно.

Но для тебя это была бы очередная практика Java + новости из интернета вы будете тянуть только через одну домашку.

2018-10-10 05:54 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/data/NewsItem.java
> +    private final String title;
Гут

2018-10-10 05:54 UTC, PStrelchenkoHH commented on app/src/main/res/layout/animal_item_news.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Попробуй поработать не с вкладкой "design", а с XML-редактором. В качестве корневого элемента можно спокойно использовать CardView. Коллеги рассказали, что были какие-то проблемы с этим, когда был ListView, но в RecyclerView все ок.

2018-10-10 05:54 UTC, PStrelchenkoHH commented on app/src/main/res/layout/animal_item_news.xml
> +    android:layout_height="@dimen/news_item_height"
Это был очередной непродуманный с моей стороны комментарий =/ 
Вопрос снят

2018-10-10 05:54 UTC, PStrelchenkoHH commented on app/src/main/res/layout/animal_item_news.xml
> +        <RelativeLayout
Здесь можно обойтись одним RelativeLayout-ом, чтобы уменьшить вложенность.

2018-10-10 05:54 UTC, PStrelchenkoHH commented on app/src/main/res/layout/default_item_news.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Аналогично снимается вопрос =)

2018-10-10 05:54 UTC, PStrelchenkoHH commented on app/src/main/res/layout/default_item_news.xml
> +    <androidx.cardview.widget.CardView xmlns:card_view="http://schemas.android.com/apk/res-auto"
Мне лично неясно, зачем они в https://developer.android.com/guide/topics/ui/layout/cardview так сделали. В корневом элементе схема XML объявлена --> андроид студия не возмущается, если удалить у child элемента. Все будет по-прежнему работать.

2018-10-10 07:22 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/NewsListAdapter.java
> +                Log.d("ViewType", "Get unknown view type");
А где взять эту утилитку, кинь ссылку, плиз

2018-10-11 20:15 UTC, zvezd04et commented on app/src/main/res/layout/animal_item_news.xml
> +        <RelativeLayout
Обошелся одним. Спасибо =)

2018-10-11 20:15 UTC, zvezd04et commented on app/src/main/res/layout/animal_item_news.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Получилось =)

2018-10-11 20:28 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/NewsListActivity.java
> +    private final NewsListAdapter.OnItemClickListener clickListener = newsItem ->
Спасибо! Аргументы приняты.

Перенес. Но если не разрастется учебное приложение, перенесу обратно. 

Мне не лениво рефакторить код =))

2018-10-12 05:23 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/data/Category.java
> +public class Category implements Serializable {
Переделал на enum

2018-10-13 16:58 UTC, PStrelchenko approved these changes
Го в четвертую ДЗ

2018-10-13 18:39 UTC, merged