added loading newsList in thread and sorted by package
zvezd04et/newsleak pull request #3
Opened 2018-10-17 18:29 UTC by zvezd04et

thread using

2018-10-20 14:15 UTC, PStrelchenko requested changes
Нужны изменения в логике.

2018-10-20 14:15 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListActivity.java
> +        SupportUtils.setVisible(progressBar, shouldShow);
Это к вопросу о том, что со временем `*Utils` класс начинает превращаться в какую-то свалку. Вот и сейчас у тебя в этом классе есть и получение числа колонок, и функция, скрывающая вьюхи. Это как бы разные вещи, нет? Хочется сделать утилитные функции для View - делай отдельный утилитный класс, разграничивай зону ответственности классов, чтобы в них не попадали лишние функции. Как только в класс попадает какая-то лишняя штука, есть вероятность, что либо ты сам будешь продолжать делать что-то не очень правильно, либо кто-то, кто придет уже на существующий проект.

2018-10-20 14:15 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListActivity.java
> +        final NewsListAdapter newsAdapter = new NewsListAdapter(this, newsItem -> NewsDetailsActivity.start(this, newsItem));
Adapter можно создать всего один раз, а потом его переиспользовать. А у тебя, получается, что ты каждый раз дергаешь запрос и создаешь новый адаптер.

2018-10-20 14:15 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListActivity.java
> +        thread = new Thread(new DataLoadUtils(new Handler(), this));
Я правильно понимаю, что у тебя каждый раз, когда пользователь сворачивает-разворачивает приложение, дергается запрос на сервер и ты обновляешь список?.. А что если у тебя каждый объект, который приходит по сети, сжирает много сетевого трафика? Похоже, что не надо так делать.
Запрос на сервер должен происходить только 1 раз, когда экран впервые стартует + каждый раз, когда пользователь этого хочет (например, сделал swipe-to-refresh).

2018-10-20 14:15 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/newsleak/utils/DataLoadUtils.java
> +public class DataLoadUtils implements Runnable {
Класс называется `Utils`, а на деле - это Runnable. Может как-то переназвать класс?..

2018-10-20 14:15 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/newsleak/utils/DataLoadUtils.java
> +    private final WeakReference<Handler> handlerRef;
Я не спорю, что так можно делать - но кажется, что это сильно усложняет понимание того, что вообще тут происходит. 

Получилось так, что ты написал какой-то странный механизм, похожий по функционалу на обычный `AsyncTask`, но без плюсов и с теми же минусами навроде отсутствия сохранения запроса при переворотах экрана. 

Хорошо, что попробовал, так сказать =) Но между использованием стандартных средств Android-а и своим творением, все-таки лучше выбрать AsyncTask. Так у тебя хотя бы код был бы в одном месте + разграничен между UI и IO потоками (в смысле, что у AsyncTask есть onPostExecute метод, который ты, по сути, сделал через `NewsListLoader`, и `onExecute`, который ты реализовал здесь. Очень трудно в кучу все собрать в голове. 

Не надо так.

2018-10-20 14:15 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListLoader.java
> +public class NewsListLoader implements Runnable {
Класс называется `Loader`-ом, но он ничего не загружает же. Он выполняет `onPostExecute` метод. Без передачи результата работы из IO потока, кстати. Какая-то странная и бесполезная штука получилась =/

2018-10-20 14:15 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/newsleak/utils/SupportUtils.java
> +    public static void setVisible(@Nullable View view, boolean isVisible) {
Отписался в каком-то классе про этот метод.

2018-10-20 14:15 UTC, PStrelchenkoHH commented on app/src/main/res/layout/activity_news_list.xml
> +        xmlns:tools="http://schemas.android.com/tools"
необязательно указывать схему `xmlns:android` в `recylcerview`, так как ты уже выше ее указал. 
А вот `tools` можно перенести наверх, тогда все твои вью внутри frame layout получат доступ к аттрибутам `tools`.

2018-10-20 14:15 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/newsleak/utils/DataLoadUtils.java
> +    public DataLoadUtils(@NonNull Handler handler, @NonNull NewsListView loadingView) {
Критикуя - предлагай =) 
Поэтому я предлагаю:

- Либо переписать эту штуку на обычный `AsyncTask`
- Либо написать это с использованием `RxJava`

В обоих случаях кода получится меньше и он будет проще и понятнее, чем конструкция из `DataLoadUtils` + `NewsListLoader`.

2018-10-20 14:15 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListActivity.java
> +        newsAdapter.replaceItems(DataUtils.generateNews());
Я думал, что смысл ДЗ № 4 - сгенерировать новости на IO потоке. А тут ты это делаешь на UI. 
Надо доделать, чтобы новости возвращались из IO потока в UI.

2018-10-20 14:15 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListActivity.java
> +        SupportUtils.setVisible(progressBar, shouldShow);
Предлагаю выделить класс `ViewUtils`, туда перенести метод `setVisible`.

2018-10-20 14:15 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListActivity.java
> +        thread = new Thread(new DataLoadUtils(new Handler(), this));
Получается, что у тебя не сохраняется запрос между переворотами экрана. 
Надо сделать так, чтобы сохранялся.

2018-10-25 19:42 UTC, PStrelchenko requested changes
Надо доработать логику сохранения запроса при перевороте.

2018-10-25 19:42 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListActivity.java
> +        disposable = Observable.fromCallable(DataUtils::generateNews)
Ты эмиттишь только один элемент --> замени `Observable` на `Single`.

2018-10-25 19:42 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListActivity.java
> +                .subscribe(this::updateNews);
Если случится какая-то ошибка в `generateNews` --> приложенька крашнется. 
Добавь сюда обработку ошибки

2018-10-25 19:42 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListActivity.java
> +        SupportUtils.disposeSafe(disposable);
Ну вот видишь, у тебя SupportUtils начинает смешивать в себе кучу-кучу разных функций, которые относятся к абсолютно разным вещам. У тебя там и функции, относящиеся ко `View`, и к `Disposable`. Не надо так делать. Утилитный класс разрастется, в него намешивается куча-куча функций. И если ты не будешь разделять функции по классам, классы будут разрастаться абсолютно неконтролируемо.

2018-10-25 19:42 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/utils/SupportUtils.java
> +    public static void disposeSafe(@Nullable Disposable disposable) {
Я по названию функции сразу не понял, что она делает. Может лучше назвать `safeDispose`? Будет более естественно с точки зрения английского языка - "безопасное освобождение".

2018-10-25 19:42 UTC, PStrelchenko commented on app/src/main/res/layout/activity_news_list.xml
> +        xmlns:tools="http://schemas.android.com/tools"
Еще раз на это обращаю внимание

2018-10-25 19:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListActivity.java
> +        disposable = Observable.fromCallable(DataUtils::generateNews)
Не заметил установки глобального error handler-а.
https://habr.com/post/422611/
https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling

2018-10-25 19:42 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListAdapter.java
> +    public class ViewHolder extends RecyclerView.ViewHolder {
Давай сделаем класс не public - он же используется только здесь.

2018-10-27 17:59 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/utils/SupportUtils.java
> +    public static void disposeSafe(@Nullable Disposable disposable) {
переименовал в disposeSafely - "освободить безопасно" =)

2018-10-27 18:00 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListAdapter.java
> +    public class ViewHolder extends RecyclerView.ViewHolder {
сделал

2018-10-27 18:08 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListActivity.java
> +        disposable = Observable.fromCallable(DataUtils::generateNews)
добавил

2018-10-27 18:09 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListActivity.java
> +                .subscribe(this::updateNews);
Добавил

2018-10-27 18:12 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListActivity.java
> +        disposable = Observable.fromCallable(DataUtils::generateNews)
Заменил

2018-10-27 18:15 UTC, zvezd04et commented on app/src/main/res/layout/activity_news_list.xml
> +        xmlns:tools="http://schemas.android.com/tools"
поправил. прошлый раз не заметил. сорян =)

2018-10-27 18:21 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListActivity.java
> +        SupportUtils.disposeSafe(disposable);
мне, кажется, это все же дело вкуса. то что утилитные методы собраны в один класс - тоже своего рода порядок. я бы разносил по "принципу кучи" если ряд методов логически связан и образуте "кучу", то нужно выносить, пока только один, то пока будет в общей куче.

https://github.com/Android-Academy-MSK/NYTimes/blob/master/app/src/main/java/ru/androidacademy/msk/nytimes/utils/Utils.java

Здесь тоже своего рода венигрет. и если он со временем разнесется, то будет тоже демонстрация того, что разносить никогда не поздно. =))

2018-10-27 18:53 UTC, PStrelchenko requested changes
Еще немного доработок.

2018-10-27 18:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListActivity.java
> +        RxJavaPlugins.setErrorHandler(ErrorHandler.get());
Это лучше устанавливать 1 раз за все приложение --> вынеси в класс Application.

2018-10-27 18:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListActivity.java
> +        RxJavaPlugins.setErrorHandler(ErrorHandler.get());
Эту штуку надо указывать только 1 раз за всю работу приложения - вынеси это в Application класс.

2018-10-27 18:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListActivity.java
> +        SupportUtils.disposeSafely(disposable);
Получается, что запрос все равно не сохраняется между переворотами экрана. Когда у тебя приложение сворачивается, ты убиваешь запрос. Это не совсем то, что ожидалось в ДЗ.

2018-10-27 18:53 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/newsleak/utils/ErrorHandler.java
> +public class ErrorHandler implements Consumer<Throwable> {
Такой дополнительный класс будет не нужен, если ты перенесешь установку global error handler-а в класс Application. Тем более, что вся твоя обработка исключения заключается в 1 строчке кода:

`Log.e(LOG_TAG, "Error on " + Thread.currentThread().getName() + ":", throwable);`

2018-10-29 05:51 UTC, PStrelchenko approved these changes
Приступай к пятой дз

2018-10-29 19:01 UTC, merged