Feature/ex 6
zvezd04et/newsleak pull request #5
Opened 2018-11-18 14:57 UTC by zvezd04et

ex-6 is done

2018-11-24 14:55 UTC, PStrelchenko requested changes
need changes

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/AndroidManifest.xml
> +            android:configChanges="orientation|screenSize"
Здесь уже этого не должно быть -- у нас же теперь данные получаются из БД, а не WebView.

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/App.java
>          RxJavaPlugins.setErrorHandler(e -> Log.d(LOG_TAG, "Error on " + Thread.currentThread().getName() + ":", e));
Все-таки напиши нормальный обработчик ошибок. Там ведь далеко не все ошибки подряд надо логировать. 
Возьми его из статьи, которую я присылал: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/App.java
> +        database = Room.databaseBuilder(this, AppDatabase.class, AppDatabase.DATABASE_NAME)
Я бы вынес построение базы в класс базы, чтоб не захламлять `App`-класс. То есть:

```
database = AppDatabase.getDatabase();
```

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/App.java
> +    public static AppDatabase getDatabase() {
Не забываем аннотации.

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/data/db/AppDatabase.java
> +    public static final String DATABASE_NAME = "newsleak.db";
Вот если перенесешь сюда метод создания БД, то и эта константа станет никому не видна, и это хорошо. Зачем другим знать, как называется файл базы?

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/intro/IntroActivity.java
> +                .delay(TIME_DELAY, TimeUnit.SECONDS)
А где определение "каждого второго раза"? Где использование shared pref?

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/intro/IntroActivity.java
> +    private CompositeDisposable compositeDisposable = new CompositeDisposable();
У тебя же теперь есть Mosby. Логика же должна находиться в presenter-е. Раз уж ввел MVP --> давай его придерживаться.

2018-11-24 14:55 UTC, PStrelchenko commented on app/build.gradle
> +    implementation "com.hannesdorfmann.mosby3:mvp-lce:$mosbyVersion"
Мы же вроде в прошлый раз решили, что Mosby - это такое себе решение. Почему бы не заменить на Moxy? Там на хабре недавно вышла статья, как все-таки можно подрубить  Moxy вместе с androix.

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/news_details/NewsDetailsActivity.java
> +        presenter.getData(newsId);
Выглядит неправильным с точки зрения MVP. Получается, что View знает, откуда она берет данные, хотя это не должно быть так. Это Presenter после аттачинга ко вью должен отправить какие-то данные в view.

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/news_details/NewsDetailsActivity.java
> +        return new NewsDetailsPresenter();
Сдается мне, что здесь можно было пробросить id прямо в презентер.

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/news_details/NewsDetailsPresenter.java
> +        id = newsItem.getId();
выглядит странно - что ты на этапе `processLoading` сохранил `id`, хотя этот `id` известен еще на момент создания presenter-а -- он прилетает из предыдущей активити

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/news_details/NewsDetailsPresenter.java
> +    private NewsDao database = App.getDatabase().getNewsDao();
можно добавить `final`

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/news_details/NewsDetailsPresenter.java
> +        compositeDisposable.add(disposable);
Зачем 2 раза добавлять ?

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/news_edit/NewsEditActivity.java
> +
пустота?.. Может какой-то комментарий надо добавить?

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/news_edit/NewsEditPresenter.java
> +        if (newsItem != null) {
Где-то это я уже видел.
Похоже, что можно общий код вынести в какой-то общий класс - `BaseNewsPresenter`

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/news_edit/NewsEditPresenter.java
> +        final Disposable disposable = database.insert(newsItem)
а почему `insert`, а не `update`? по логике-то тут совершается именно `update`

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/news_edit/NewsEditActivity.java
> +        newsItem.setTitle(titleEdit.getText().toString());
Опять неправильно с точки зрения архитектуры. Почему View обновляет какие-то данные? Ты должен был собрать какие-то данные для обновления из View и пробросить их в presenter, а тот уже будет с ними дальше работать. 
А здесь получается, что View сама знает как и что делать с сущностями, какую бизнес-логику ей выполнять.

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListAdapter.java
> +            if (hasUrl) imageLoader.load(newsItem.getNormalImageUrl()).into(photoView);
фигурные скобки не забываем

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/res/layout/activity_news_details.xml
> +            app:layout_scrollFlags="scroll|exitUntilCollapsed"
можно еще `|snap` добавить, чтоб не было полуанимированного состояния

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/utils/NewsItemConverter.java
> +    public static Date toDate(Long dateLong) {
Я бы вынес TypeConverter-ы в отдельный класс. Для Date - один класс. Для Category - другой. 
Иначе опять у тебя сборная солянка получается. Вроде как класс называется NewsConverter. А тут и конвертеры для дат, для категорий, для новостей.

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/model/NewsItem.java
> +@TypeConverters(NewsItemConverter.class)
Уверен, что это здесь надо указывать? Можно же на database класс навесить, и тогда не придется над каждым классом такую штуку юзать.

2018-11-24 14:55 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/utils/NewsItemConverter.java
> +    public static Date toDate(Long dateLong) {
Или же в один класс - но обозвать его как-то понятно, чтобы другие люди могли понять, что это класс, который содержит все TypeConverter-ы для базы данных

2018-11-24 20:36 UTC, zvezd04et commented on app/src/main/AndroidManifest.xml
> +            android:configChanges="orientation|screenSize"
убрал

2018-11-24 20:41 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/App.java
>          RxJavaPlugins.setErrorHandler(e -> Log.d(LOG_TAG, "Error on " + Thread.currentThread().getName() + ":", e));
переписал

2018-11-25 09:33 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/App.java
> +        database = Room.databaseBuilder(this, AppDatabase.class, AppDatabase.DATABASE_NAME)
вынес

2018-11-25 09:35 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/App.java
> +    public static AppDatabase getDatabase() {
добавил

2018-11-25 09:35 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/data/db/AppDatabase.java
> +    public static final String DATABASE_NAME = "newsleak.db";
не зачем =)

2018-11-25 13:21 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/intro/IntroActivity.java
> +                .delay(TIME_DELAY, TimeUnit.SECONDS)
Сорян, пропустил. Теперь добавил =)

2018-11-25 13:21 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/intro/IntroActivity.java
> +    private CompositeDisposable compositeDisposable = new CompositeDisposable();
Давай

2018-11-25 13:23 UTC, zvezd04et commented on app/build.gradle
> +    implementation "com.hannesdorfmann.mosby3:mvp-lce:$mosbyVersion"
пока оставлю, вроде с задачами справляется из коробки

2018-11-25 14:03 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/news_details/NewsDetailsActivity.java
> +        presenter.getData(newsId);
Я понял про что ты. Mosby так не может :(

Посмотри, плиз. Если мигрировать на ViewModel, там такой подход применим ведь?
https://developer.android.com/topic/libraries/architecture/viewmodel#java

2018-11-25 14:10 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/news_details/NewsDetailsActivity.java
> +        return new NewsDetailsPresenter();
переделал

2018-11-25 14:10 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/news_details/NewsDetailsPresenter.java
> +        id = newsItem.getId();
ты прав, не зачем

2018-11-25 14:11 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/news_details/NewsDetailsPresenter.java
> +    private NewsDao database = App.getDatabase().getNewsDao();
добавил

2018-11-25 14:11 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/news_details/NewsDetailsPresenter.java
> +        compositeDisposable.add(disposable);
чтоб наверняка =)) опечатка

2018-11-25 16:53 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/news_edit/NewsEditActivity.java
> +
добавил коммент

2018-11-25 16:53 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/news_edit/NewsEditPresenter.java
> +        if (newsItem != null) {
вынес

2018-11-25 17:02 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/news_edit/NewsEditPresenter.java
> +        final Disposable disposable = database.insert(newsItem)
тупо скопировал со слайда начальника твоего =)

переименовал

2018-11-25 17:27 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/news_edit/NewsEditActivity.java
> +        newsItem.setTitle(titleEdit.getText().toString());
отрефакторил

2018-11-25 17:31 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListAdapter.java
> +            if (hasUrl) imageLoader.load(newsItem.getNormalImageUrl()).into(photoView);
добавил

2018-11-25 17:34 UTC, zvezd04et commented on app/src/main/res/layout/activity_news_details.xml
> +            app:layout_scrollFlags="scroll|exitUntilCollapsed"
добавил

2018-11-25 17:35 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/utils/NewsItemConverter.java
> +    public static Date toDate(Long dateLong) {
сделал в один класс, чтобы можно было указать для database класс один раз

2018-11-25 17:37 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/utils/NewsItemConverter.java
> +    public static Date toDate(Long dateLong) {
здесь, вообще, название простецкое:
https://developer.android.com/reference/android/arch/persistence/room/TypeConverter

Но назвал по аналогии =)

2018-11-25 17:37 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/model/NewsItem.java
> +@TypeConverters(NewsItemConverter.class)
перевесил

2018-11-25 17:38 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/news_details/NewsDetailsActivity.java
> +        presenter.getData(newsId);
Переписал, добавил чуточку Moxy ;))

2018-12-01 07:54 UTC, PStrelchenko approved these changes
Взгляд ни за что не зацепился =) Апрув.

2018-12-01 07:54 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/newsleak/features/news_details/NewsDetailsActivity.java
> +import java.util.concurrent.Callable;
Лишний импорт?

2018-12-01 16:24 UTC, merged