Feature/ex 8
zvezd04et/newsleak pull request #7
Opened 2018-12-13 20:03 UTC by zvezd04et

ex-8 is done

2019-01-08 15:47 UTC, PStrelchenko requested changes
Предлагаю изменения

2019-01-08 15:47 UTC, PStrelchenko commented on app/build.gradle
> +    implementation "android.arch.work:work-runtime:1.0.0-alpha11"
И как тебе не стремно втягивать alpha-версии библиотек?.. 
Главное на проде так не делай. Пока workmanager не зарелижен, можно пользоваться evernote-job. Правда, и у него есть определенные проблемы на 8 андроиде

2019-01-08 15:47 UTC, PStrelchenko commented on app/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
Неконсистентненько выглядит использование версий - то ты используешь какие-то константки вида `$jetVersion`, то напрямую версии фигачишь. Выбери что-то одно. 
Лучше - константки, чтобы, если задумаешь делать многомодульный проект, можно было их везде использовать

2019-01-08 15:47 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/App.java
> +        final Constraints constraints = new Constraints.Builder()
Я бы вынес эту логику в отдельный класс, чтобы не загромождать Application класс. У тебя он уже и так не очень маленький. 
Создай какой-нить NewsUpdateScheduler и туда перемести логику, а из application просто дергай метод этого scheduler-а.

2019-01-08 15:47 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/App.java
> +        final Constraints constraints = new Constraints.Builder()
Под "этой логикой" я имею в виду весь метод setupWorkManager

2019-01-08 15:47 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/data/api/ApiKeyInterceptor.java
> +    private ApiKeyInterceptor(@NonNull String apiKey) {
Что-то здесь я упустил - зачем вообще тут статический метод создания интерсептора? Почему обычный public конструктор не подходит? Почему бы вообще его через Dagger в нужное место не подставлять?

2019-01-08 15:47 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/data/db/NewsRepository.java
> +    private NewsDao newsDao;
Нужно ли оставлять возможность подменить NewsDao во время работы программы? Это к тому, что нет модификатора final

2019-01-08 15:47 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/data/db/NewsRepository.java
> +    public Observable<NewsItem> getItemObservable(int id) {
Интовый id-шник? Наверное, в нашем случае OK, но я бы использовал long - привычка, оставшаяся после работы на бекенде.

2019-01-08 15:47 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/di/modules/AppModule.java
> +    private Context appContext;
Я б добавил final. Особого смысла это не имеет - только ради того, чтобы гарантировать неизменность appContext-а

2019-01-08 15:47 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/di/modules/DbModule.java
> +        final AppDatabase database = Room.databaseBuilder(context.getApplicationContext(),
Нууу... Такое себе =) 
Создается впечатление, что если потребуется очередной DAO ты скопируешь этот кусок кода и подменишь вызов `database.getNewsDao` на `database.getAnotherDao`. 

Базу данных надо создать только один раз. Можешь оставить здесь (в смысле в DbModule) метод создания БД, а потом использовать ее для получения DAO:

```
@Provides
@Singleton
@NonNull
AppDatabase provideDatabase(@NonNull Context context) {
    return Room.databaseBuilder(
        context.getApplicationContext, 
        AppDatabase.class, 
        Constant.DATABASE_NAME
    )
    .build();
}

@Providers
@Singleton
@NonNull
NewsDao provideNewsDao(@NonNull AppDatabase database) {
    return database.getNewsDao();
}
```

2019-01-08 15:47 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/news_details/NewsDetailsFragment.java
> +        App.getAppComponent().plus(new NewsItemModule(newsId)).inject(this);
Я бы вынес логику создания всяких там компонентов в отдельный класс - DI со статическими методами, чтобы, опять же, не перегружать другие классы не важной для них логикой. 
Апи был бы таким:

```
DI.getNewsDetailsComponent(newsId).inject(this);
```

И класс DI был бы единым местом работы с DI. По мне так норм, а тебе как кажется?

2019-01-08 15:47 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/news_edit/NewsEditActivity.java
> +        App.getAppComponent().plus(new NewsItemModule(newsId)).inject(this);
Аналогично про DI класс задвигаю

2019-01-08 15:47 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/news_edit/NewsEditActivity.java
> +        App.getAppComponent().plus(new NewsItemModule(newsId)).inject(this);
Кстати, по поводу inject-а id-шника напрямую: в последнее время завел себе привычку сразу создавать какую-то модельку специально для inject-а каких-либо данных. В данном случае, что-то типо:
```
public final class NewsItemData {
    private final int newsId;

    public NewsItemModule(int newsId) {
        this.newsId = newsId;
    }
}
```

Зачем - часто возникает необходимость добавить какое-то дополнительное поле для inject-а. И вместо того, чтобы менять сразу тучу мест (проброс в класс DI, проброс из Module-класса, проброс в конструктор presenter-а) - можно будет заменить только проброс в DI, и создание модельки. И дальше уже использовать как угодно.

2019-01-08 15:47 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListPresenter.java
> +        RxUtils.disposeSafely(disposable);
Это же уже в BasePresenter-е есть?

2019-01-08 15:47 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListPresenter.java
> +        disposable = api
Почему этот disposable нельзя добавлять в compositeDisposable?

2019-01-08 17:05 UTC, zvezd04et commented on app/build.gradle
> +    implementation "android.arch.work:work-runtime:1.0.0-alpha11"
За сим (WorkManager) воля Мацюка была =))

2019-01-08 17:07 UTC, zvezd04et commented on app/build.gradle
> +    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
оконстантил

2019-01-08 17:34 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/App.java
> +        final Constraints constraints = new Constraints.Builder()
перенес в NewsUpdateWorker

2019-01-08 17:44 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/data/api/ApiKeyInterceptor.java
> +    private ApiKeyInterceptor(@NonNull String apiKey) {
прокинул через Dagger

2019-01-08 18:01 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/data/db/NewsRepository.java
> +    private NewsDao newsDao;
добавил

2019-01-08 18:01 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/di/modules/AppModule.java
> +    private Context appContext;
добавил

2019-01-08 18:02 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListPresenter.java
> +        disposable = api
В самом деле почему? =) Переделал

2019-01-08 18:02 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/newsfeed/NewsListPresenter.java
> +        RxUtils.disposeSafely(disposable);
Ага, поправил

2019-01-08 18:12 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/di/modules/DbModule.java
> +        final AppDatabase database = Room.databaseBuilder(context.getApplicationContext(),
переделал

2019-01-08 19:08 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/news_details/NewsDetailsFragment.java
> +        App.getAppComponent().plus(new NewsItemModule(newsId)).inject(this);
Мне нравится =) Добавил класс DI

2019-01-08 19:16 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/features/news_edit/NewsEditActivity.java
> +        App.getAppComponent().plus(new NewsItemModule(newsId)).inject(this);
Про класс принято

За способ проброса отдельное спасибо. Учту на будущее. Но в данном конкретном случае применять не вижу особого смысла.

2019-01-08 19:17 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/Constant.java
> +    public static final String DATABASE_NAME = "newsleak.db";
Здесь для единообразия, чтобы все константы были под рукой =)

2019-01-08 19:29 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/data/db/NewsRepository.java
> +    public Observable<NewsItem> getItemObservable(int id) {
База у нас не пухнет. Перед каждой загрузкой записи очищаются, так что в нашем случае, думаю, все ОК =)

За то что обратил внимание спасибо

2019-01-10 07:27 UTC, PStrelchenko requested changes
Предлагаю еще несколько изменений

2019-01-10 07:27 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/Constant.java
> +    public static final String DATABASE_NAME = "newsleak.db";
Ок.

2019-01-10 07:27 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/data/db/NewsRepository.java
> +    public Observable<NewsItem> getItemObservable(int id) {
ок

2019-01-10 07:27 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/service/NewsUpdateService.java
> +    private static PendingIntent getStopPendingIntent(Context context) {
Почему этот метод именно статический? вроде бы используется только в нестатическом контексте.

2019-01-10 07:27 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/service/NewsUpdateService.java
> +public class NewsUpdateService extends Service {
Вообще, конечно, этот сервис у тебя получился каким-то монстром - в нем есть и функционал нотификаций, и какая-то работа с сетью, и еще сохранение чего-то в префы.
Есть ощущение, что какой-то функционал можно аккуратно отсюда вынести и сделать код покомпактнее.

Например - все, что связано с нотификациями. Сделать класс-обертку над NotificationManager. В нем создавать pendingIntent, в нем создавать нужный notification. Действие при клике на pending intent - пробрасывать через листенер, например.

Обновление новостей - я бы вынес в какой-нить интерактор. То есть создание всей этой вот цепочки rx-овой - туда. 

Так код в этом классе станет понятнее и компактнее. 
Что думаешь?

2019-01-10 07:27 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/service/NewsUpdateService.java
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
Разве для запуска foregroundService-а обязателен API >= 26? 

Я бы переделал. Сервисы в чем-то похожи на Activity, когда мы пишем код для их запуска. В самом сервисе делаем несколько статических методов - которые нам создают Intent-ы для запуска в различных режимах.
Например:

```
public static Intent getForegroundServiceIntent(@NonNull Context context) {
    ...
}

public static Intent getServiceIntent( ... ) 
```

А потом мы их запускаем просто через context.startService(intent) в том месте, где надо.

2019-01-10 07:27 UTC, PStrelchenko commented on app/src/main/java/com/z/newsleak/utils/NetworkUtils.java
> +    public void registerNetworkCallback() {
Честно говоря, не понимаю, зачем тебе запуск этого метода именно в классе Application. почему бы не зарегистрировать callback уже в конструкторе? Не потребуется никакой инжект в App-класс.

2019-01-12 09:25 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/service/NewsUpdateService.java
> +    private static PendingIntent getStopPendingIntent(Context context) {
Теперь этот метод public =))

2019-01-12 09:26 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/service/NewsUpdateService.java
> +public class NewsUpdateService extends Service {
Дааа, уж...

Спасибо, что обратил внимание =)

2019-01-12 09:27 UTC, zvezd04et commented on app/src/main/java/com/z/newsleak/utils/NetworkUtils.java
> +    public void registerNetworkCallback() {
Перенес в конструктор

2019-01-12 10:31 UTC, PStrelchenko approved these changes
Апруф

2019-01-12 10:31 UTC, PStrelchenkoHH commented on app/src/main/java/com/z/newsleak/service/NewsUpdateService.java
> +        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
Блин, реально не заметил строчку ` startForeground(NOTIFICATION_NEWS_UPDATE_ID, notification);` 
Сорямба

2019-01-12 10:56 UTC, merged